name: Pull Request Template
description: Template to guide pull request submissions
title: "[PR] - "
labels: "enhancement"
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Please include a summary of the changes and the issue this PR addresses.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a short description of the changes.
      placeholder: Brief description of the PR.
      required: true

  - type: input
    id: issue
    attributes:
      label: Related Issue(s)
      description: Link the issue(s) this PR addresses (e.g., #123).
      placeholder: #123
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Provide a detailed explanation of the solution implemented.
      placeholder: Detailed solution explanation.
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: PR Checklist
      options:
        - label: Code follows the project's style guidelines
          required: true
        - label: Code has been tested and passes all relevant tests
          required: true
        - label: Documentation has been updated if necessary
          required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any additional information to help reviewers.
      placeholder: Any extra details or information for reviewers.
      required: false
